name: analyzer_query
description: "A Flutter project for extending analyzer, to get data of code easily."

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  analyzer: 6.2.0 #语法树解析
  dart_style: 2.3.4 #代码自动格式化
  cupertino_icons: ^1.0.6
  pub_semver: 2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
